version: '3.4'

volumes:
  mongodb:

services:
  mongo:
    image: mongo:4.4.10-focal
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: 'admin'
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'pass'
      MONGO_USERNAME: 'user'
      MONGO_PASSWORD: 'pass'
      MONGO_DATABASE: 'linebot'
    volumes:
      - mongodb:/data/db
      - ./mongodb/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_OPTIONS_EDITORTHEME: mbo
      ME_CONFIG_MONGODB_AUTH_DATABASE: 'linebot'
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'pass'
